language: objective-c

xcode_project: "Tools Test App.xcodeproj" # path to your xcodeproj folder
xcode_scheme: "Tools Test App"
osx_image: xcode8.2

before_script:
  - xcrun simctl delete 1FD54EA7-5A25-4D6F-8599-D6F7687DA4EE
script:
  - ./bin/test.sh
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Tools Test App'

addons:
    code_climate:
        repo_token: 9341b8c6ef34ef5cfcb09547994c5d1377e442c6e3bfaa2cae2a6c1cc8c086ad
